# Generated by Django 3.2.7 on 2021-10-14 03:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('prod_id', models.AutoField(primary_key=True, serialize=False)),
                ('prod_name', models.CharField(default=0, max_length=30, verbose_name='Name')),
                ('prod_artist', models.CharField(default=0, max_length=30, verbose_name='Artist')),
                ('prod_genre', models.CharField(default=0, max_length=15, verbose_name='Genre')),
                ('prod_rate', models.BigIntegerField(verbose_name='Rate')),
                ('prod_type', models.CharField(default=0, max_length=15, verbose_name='Type')),
                ('prod_description', models.CharField(default=0, max_length=50, verbose_name='Description')),
                ('prod_urlproduct', models.CharField(default=0, max_length=15, verbose_name='imagen')),
                ('prod_urlimagen', models.CharField(default=0, max_length=15, verbose_name='imagen')),
                ('prod_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_producto', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
