# Generated by Django 3.2.7 on 2021-10-15 02:08

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0002_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('exch_id', models.AutoField(primary_key=True, serialize=False)),
                ('exch_fecha', models.DateTimeField(default=datetime.datetime.now)),
                ('exch_prod_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exch_prod', to='authApp.product')),
                ('exch_userdestination_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exch_userdestination', to=settings.AUTH_USER_MODEL)),
                ('exch_userorigin_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exch_userorigin', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
