# Generated by Django 3.2.7 on 2021-10-15 03:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0003_exchange'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exchange',
            old_name='exch_prod_id',
            new_name='exch_prod',
        ),
        migrations.RenameField(
            model_name='exchange',
            old_name='exch_userdestination_id',
            new_name='exch_userdestination',
        ),
        migrations.RenameField(
            model_name='exchange',
            old_name='exch_userorigin_id',
            new_name='exch_userorigin',
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('favo_id', models.AutoField(primary_key=True, serialize=False)),
                ('favo_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favo_product', to='authApp.product')),
                ('favo_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favo_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
